import {
  pyenvStep,
  nvmStep,
  rustupStep,
  homebrewStep,
  masStep,
  ohmyzshStep,
  npmStep,
  pipStep,
  uvStep,
  ghStep,
  dotnetStep,
  aspireStep,
  macosStep,
  cleanupStep,
  braeburnStep,
  type Step,
} from "./index.js";

const STEP_BY_ID: Record<string, Step> = {
  pyenv: pyenvStep,
  nvm: nvmStep,
  rustup: rustupStep,
  homebrew: homebrewStep,
  mas: masStep,
  macos: macosStep,
  npm: npmStep,
  pip: pipStep,
  uv: uvStep,
  gh: ghStep,
  dotnet: dotnetStep,
  aspire: aspireStep,
  ohmyzsh: ohmyzshStep,
  cleanup: cleanupStep,
  braeburn: braeburnStep,
};

const STEP_EXECUTION_ORDER: string[] = [
  "pyenv",
  "nvm",
  "rustup",
  "homebrew",
  "mas",
  "macos",
  "npm",
  "braeburn",
  "pip",
  "uv",
  "gh",
  "dotnet",
  "aspire",
  "ohmyzsh",
  "cleanup",
];

export const ALL_STEPS: Step[] = STEP_EXECUTION_ORDER.map((stepId) => STEP_BY_ID[stepId]);
